version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Download rustup
          command: |
            wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
            chmod +x rustup-init
      - run:
          name: Install Rust
          command: |
            ./rustup-init -y --no-modify-path --default-toolchain nightly
            rm rustup-init
            echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Tarpaulin
          command: cargo install cargo-tarpaulin
          environment:
            RUSTFLAGS: --cfg procmacro2_semver_exempt
      - run:
          name: Generate coverage report
          command: docker run -e DATABASE_URL_TEST_BASE=$DATABASE_URL_TEST_BASE --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin
